services:
  api:
    build: ./Backend
    ports:
      - 8080:8080
    links:
      - db:database
    environment:
      - PG_Name=science_data
      - PG_Username=labAdmin
      - PG_Password=labPassword
      - FRONT_URL=http://localhost:3000
    depends_on:
      - db
      
  front:
    build: ./Frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8080/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./Frontend:/app/frontend
      - /app/frontend/node_modules
    develop:
      watch:
        - action: sync
          path: ./Frontend
          target: /app/frontend
          ignore:
            - node_modules/
            - dist/
            - .yarn/

  db:
    image: postgres:17.6
    volumes:
      - science-data:/var/lib/postgresql/scienceData
    ports:
      - 12345:5432
    environment:
      - POSTGRES_DB=science_data
      - POSTGRES_USER=labAdmin
      - POSTGRES_PASSWORD=labPassword

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  science-data: 