services:
  api:
    build: ./Backend
    ports:
      - 8080:8080
    links:
      - db:database
    environment:
      - PG_Name=labDb
      - PG_Username=labAdmin
      - PG_Password=labPassword
      - FRONT_URL=http://localhost:3000
    depends_on:
      - db
      
  front:
    build: ./Frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8080
    develop:
      watch:
        - action: sync
          path: ./Frontend
          target: /app/frontend
          ignore:
            - node_modules/
              dist/
              .yarn/

  db:
    image: postgres:17.6
    volumes:
      - lab-data:/var/lib/postgresql/labData
    ports:
      - 12345:5432
    environment:
      - POSTGRES_DB=labDb
      - POSTGRES_USER=labAdmin
      - POSTGRES_PASSWORD=labPassword

volumes:
  lab-data: 