spring.application.name=LabNotes
springdoc.api-docs.path=/docs
spring.datasource.url=jdbc:postgresql://db:5432/${PG_Name}
spring.datasource.username=${PG_Username}
spring.datasource.password=${PG_Password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.ddl-auto=update
spring.jpa.database-platform=prg.hibernate.dialect.PostgreSQLDialect
