spring.application.name=LabNotes
springdoc.api-docs.path=/docs
spring.datasource.url=jdbc:postgresql://db:5432/${PG_Name}
spring.datasource.username=${PG_Username}
spring.datasource.password=${PG_Password}
spring.jpa.generate-ddl=true
spring.jpa.database-platform=prg.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/api